import { motion } from "framer-motion";
import { useState } from "react";
import { Shield, ShieldAlert, MonitorSmartphone, Key, Smartphone, AlertTriangle } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/layouts/PageHeader";
import { Button } from "@/components/ui/button";

export default function AccountSecurity() {
  const [twoFactor, setTwoFactor] = useState(false);

  const toggle2FA = () => {
    setTwoFactor(!twoFactor);
    toast.success(`Two-factor authentication ${!twoFactor ? 'enabled' : 'disabled'}`);
  };

  return (
    <div>
      <PageHeader
        title="Security"
        description="Manage your account security and authentication methods."
        breadcrumbs={[{ label: "Account", to: "/account/security" }, { label: "Security" }]} />

      <div className="grid gap-6 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="rounded-2xl border border-sidebar-border bg-sidebar/50 p-6 shadow-sm">
          
          <div className="flex items-start justify-between gap-4">
            <div className="space-y-1">
              <h3 className="text-lg font-semibold flex items-center gap-2">
                <Shield className="h-5 w-5 text-primary" />
                Two-factor authentication (2FA)
              </h3>
              <p className="text-sm text-muted-foreground">
                Add an extra layer of security to your account by requiring more than just your password to sign in.
              </p>
            </div>
            <Button variant={twoFactor ? "destructive" : "default"} onClick={toggle2FA}>
              {twoFactor ? "Disable" : "Enable"}
            </Button>
          </div>
          
          {twoFactor && (
            <div className="mt-6 rounded-lg border border-primary/20 bg-primary/5 p-4 flex items-start gap-3">
              <Smartphone className="h-5 w-5 text-primary mt-0.5" />
              <div>
                <p className="font-medium text-primary">Authenticator App Active</p>
                <p className="text-sm text-muted-foreground">Verification codes are generated by your authenticator app.</p>
              </div>
            </div>
          )}
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: 0.1 }}
          className="rounded-2xl border border-sidebar-border bg-sidebar/50 p-6 shadow-sm">
          
          <h3 className="text-lg font-semibold flex items-center gap-2 mb-4">
            <MonitorSmartphone className="h-5 w-5 text-muted-foreground" />
            Active Sessions
          </h3>
          <p className="text-sm text-muted-foreground mb-6">
            These are the devices that have logged into your account. Revoke any sessions that you do not recognize.
          </p>

          <div className="space-y-4">
            <div className="flex items-center justify-between p-4 rounded-lg border border-sidebar-border bg-background">
              <div className="flex items-center gap-4">
                <MonitorSmartphone className="h-8 w-8 text-foreground" />
                <div>
                  <p className="font-medium text-foreground">Windows • Chrome</p>
                  <p className="text-xs text-muted-foreground">Kigali, Rwanda • Current session</p>
                </div>
              </div>
              <span className="text-xs font-semibold text-primary bg-primary/10 px-2.5 py-1 rounded-full">Active</span>
            </div>

            <div className="flex items-center justify-between p-4 rounded-lg border border-sidebar-border bg-background">
              <div className="flex items-center gap-4">
                <Smartphone className="h-8 w-8 text-muted-foreground" />
                <div>
                  <p className="font-medium text-foreground">iPhone 13 • Safari</p>
                  <p className="text-xs text-muted-foreground">Kigali, Rwanda • Last active 2 days ago</p>
                </div>
              </div>
              <Button variant="outline" size="sm" onClick={() => toast.success("Session revoked")}>Revoke</Button>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
